### ISSUE TITLE
RoadmapTimelineElement Component

### ISSUE THREAD

**Issue by galileo** [x-team/auto-ui#10]
Represents the single step from the timeline.

done: **false**
![screenshot from 2017-11-06 14-01-34](https://user-images.githubusercontent.com/39776/32442375-80e7a306-c2fb-11e7-826d-f9c51414a3c1.png)

done: **true**
![screenshot from 2017-11-06 14-01-00](https://user-images.githubusercontent.com/39776/32442376-80ff481c-c2fb-11e7-8d28-3929fcb4aa9e.png)

## Props
```
isDone: boolean
```

**Done**

Recognizes for the element state

**Comment by nicksp** [comment]
@galileo How is it going with this component? Are you wish to complete it or maybe need any help?

**Comment by galileo** [comment]
@nicksp I will start it right now.
