### ISSUE TITLE
Textarea component

### ISSUE THREAD

**Issue by bernardodiasc** [x-team/auto-ui#102]
Create new UI component: **Textarea**

## Preview

![textarea](https://user-images.githubusercontent.com/131859/35111153-b91d5ce4-fc61-11e7-8dbe-fac07d5f4dc1.png)

## Props

```
placeholder: string
children: node
onChange: function
onFocus: function
onUnfocus: function
charLimit: number (default to 1000)
```

## Behaviour

- The Textarea component should be based on https://github.com/ngs/draft-js-markdown-shortcuts-plugin (need trial with that)
- When Textarea changes, trigger action from container given on `onChange`
- When Textarea gain focus, trigger action from container given on `onFocus`
- When Textarea loses focus, trigger action from container given on `onUnfocus`
- Textarea should limit the characters to 1000 (variations can be set by `charLimit`)
- The character counter should appear when textarea is focused

**Comment by falcoagustin** [comment]
We have an input where you can pass a type and accepts a textarea as such in `auto-ui`. Maybe we can reuse that component @bernardodiasc ?

**Comment by bernardodiasc** [comment]
I'm not sure it worth to use existing one, this one have very specifics features and behaviours. If you didn't used Draft.js before, I think you'll get what I mean when you start doing this task :)

**Comment by nicksp** [comment]
If that's what I think about, on my prev project i created a component similat to GH's one with Write and Preview tabs. If that's what we need I can share it to save our time :)

![image](https://user-images.githubusercontent.com/579331/35115946-d095d64c-fc9a-11e7-8abe-a9d7658b1fea.png)

**Comment by bernardodiasc** [comment]
If the name confuses with the existing input, try something more descriptive like Markdown, MarkdownArea, SuperCoolTextarea, so something like that 😄

**Comment by falcoagustin** [comment]
Understood, thanks for the clarification @bernardodiasc

**Comment by bernardodiasc** [comment]
imho, go for it :)
I think @nicksp would agree as well, as his example above referring GH comments have that.

**Comment by nicksp** [comment]
yep, let's do that.
