### ISSUE TITLE
AttachFiles component

### ISSUE THREAD

**Issue by bernardodiasc** [x-team/auto-ui#103]
Create new component: **AttachFiles**

## Preview

![attach](https://user-images.githubusercontent.com/131859/35111093-902e0c16-fc61-11e7-80ae-82196bf8ac1f.png)

## Props

```
files: [
  {
    filename: string,
    path: string,
    progress: number
  }
]
onUpload: function
onCancel: function
onDelete: function
```

## Behaviour

- the "Attach a File" button opens the standard file picker dialog
- files that are uploading show a progress bar, and can be canceled (with confirmation)
- files that have finished uploading can be deleted (with confirmation)

**Comment by nicksp** [comment]
CLosed via https://github.com/x-team/auto-ui/pull/106
