### ISSUE TITLE
FilterBar component

### ISSUE THREAD

**Issue by bernardodiasc** [x-team/auto-ui#114]
Create **FilterBar** component

## Usage

```jsx
<FilterBar onSubmit={handleSubmit}>
  <InputField />
  <AnythingElse />
</FilterBar>
```

## Behaviour

- FieldBar contains a form that submit results using `onSubmit` prop function
- Childrens are expected to be inputs, but can be anything

**Comment by nicksp** [comment]
Just wonder if this is taken and ready for review? If so, please assign yourself and set an appropriate label. This makes life much easier :-)
