### ISSUE TITLE
Text component

### ISSUE THREAD

**Issue by bernardodiasc** [x-team/auto-ui#12]
**Epic** https://github.com/x-team/auto/issues/573

---

Create new component to render typographic content.

<img width="1300" alt="screen shot 2017-11-07 at 8 04 37 am" src="https://user-images.githubusercontent.com/131859/32490064-15fd5ed4-c399-11e7-899e-5a14e5ce4e36.png">

### Props

```
[TBD]
```

### Behaviour

This component contain all variation of styles for typography blocks (TBD on props).

**Comment by joshwnj** [comment]
@bernardodiasc I think `Text` might be a clearer name, as `Copy` can suffer from verb/noun confusion.

I'm also fine with combining `PageTitle` into this, and having a single "heading + divider + subheading + text" component.

**Comment by nicksp** [comment]
@bernardodiasc Seems like PR is merged for that. Can we close it then?

**Comment by bernardodiasc** [comment]
yep :)
