### ISSUE TITLE
Graphic component

### ISSUE THREAD

**Issue by bernardodiasc** [x-team/auto-ui#13]
**Epic** https://github.com/x-team/auto/issues/573

---

Create new component to render graphics.

<img width="1054" alt="screen shot 2017-11-07 at 8 06 39 am" src="https://user-images.githubusercontent.com/131859/32488147-d45764b2-c392-11e7-8d26-0de308f89639.png">
<img width="141" alt="screen shot 2017-11-07 at 10 56 47 am" src="https://user-images.githubusercontent.com/131859/32494837-619e2a4c-c3aa-11e7-8c15-da96f913e716.png"><img width="107" alt="screen shot 2017-11-07 at 10 57 31 am" src="https://user-images.githubusercontent.com/131859/32494857-7ae570a0-c3aa-11e7-8fcd-414c22d53634.png">
<img width="1071" alt="screen shot 2017-11-07 at 10 57 15 am" src="https://user-images.githubusercontent.com/131859/32494862-7f6cc61e-c3aa-11e7-9820-a7b94a18e2ee.png">

### Props

```
id: string,
className: object,
```

### Behaviour

Graphics can be styled in many different ways in the page, this component is **not** meant to provide layout options for the graphic. It main purpose is to encapsulate defaults `<img>` and `<svg>` HTML tags and centralize it's behaviours. 

- It should accept `...props`  and pass it to the html tag (the availables for `<img>` and `<svg>`)
- if `id` is invalid, render `null`
- (optional) create 404 render for `onError` event, accepted by `<img>` tag
- this component stores all the images available in the UI set, for layout purposes, not content. the `id` will map to the correct render.

**Comment by joshwnj** [comment]
@bernardodiasc I'm not 100% sure about the value of this yet, rather than just using `<img>` or `<svg>` elements directly within other components... Even though this is listed as a dependency of other components, let's try building some of those larger components first without it, and see whether the need for it becomes clearer.

**Comment by bernardodiasc** [comment]
Alright, that sounds reasonable. This component might not be needed at all. The use case I had before was to render custom 404 images, something useful for large databases and scenarios where images url can break more often, like large news websites, definitely not this case.

There was another use case, that was on styles matter. Instead using global css for `img` selector, we used a `Image` component for all `<img>` uses in the app. The styles in that cases had element isolation  (reset css) and the `max-width: 100%;`. Again, no big deal, I think this one can be skipped. :)

**Comment by bernardodiasc** [comment]
Just for the record, this is what I have:

```js
import React, { PropTypes } from 'react';
import classNames from 'classnames';
import { compose, withState, onlyUpdateForKeys } from 'recompose';
import notFoundImage from 'file-loader!./not-found.png';

/**
 * Image React component
 * @param  {string}     options.src           src attr for <img />
 * @param  {string}     options.alt           alt attr for <img />
 * @param  {string}     options.classNames    aditional className from parent component
 * @param  {bool}       options.error         default to false, will become true when <img /> return onError
 * @param  {func}       options.handleError   function to change error state value
 * @param  {object}     options.theme         theme object with all css classNames
 * @param  {...object}  options.rest          any unpredicted prop
 * @return {component}                        react component
 */
const Image = ({ src, alt, className, error, handleError, theme, ...rest }) => (
  <img
    className={classNames(theme.image, className)}
    src={error ? notFoundImage : src}
    alt={alt}
    onError={() => handleError(true)}
    {...rest}
  />
);

Image.propTypes = {
  src: PropTypes.string.isRequired,
  alt: PropTypes.string,
  className: PropTypes.string,
  error: PropTypes.bool,
  handleError: PropTypes.func,
  theme: PropTypes.shape({
    image: PropTypes.string,
  }).isRequired,
};

Image.defaultProps = {
  alt: '',
};

export default compose(
  withState('error', 'handleError', false),
  onlyUpdateForKeys(['error']),
)(Image);
```

**Comment by joshwnj** [comment]
> The use case I had before was to render custom 404 images, something useful for large databases and scenarios where images url can break more often, like large news websites, definitely not this case.

This makes total sense if the images are coming from some outside source, or user uploads.  But in our case we can 100% assume that the images are available.

Let's close this one for now, and revisit if we have a case in future where we need to display images that are < 100% reliable.
