### ISSUE TITLE
Avatar Component

### ISSUE THREAD

**Issue by jepz20** [x-team/auto-ui#137]
Mockup

![image](https://user-images.githubusercontent.com/4315829/40136205-37f57474-5915-11e8-921e-67bb2b01d216.png)

Given an image url return a rounded avatar(to be used on #127)

**Comment by slawekkolodziej** [comment]
What about avatar size? Should we use fixed size (right now it's 64px) or maybe we should pass `size` prop instead? Eg.:
```
<Avatar src="/foo.png" alt="my avatar" size={32} />
```

**Comment by nicksp** [comment]
Closed via https://github.com/x-team/auto-ui/pull/139
