### ISSUE TITLE
Include read only state on TextareaEditor

### ISSUE THREAD

**Issue by bernardodiasc** [x-team/auto-ui#143]
## User story

As a developer, I want to use `<TextareaEditor />` with a read only state.

### JSX API

```jsx
<TextareaEditor
  disableEditing
  text="Text Area #1  With Formatted Text"
  html="<div>Text Area x-team/auto-ui#1 <b>With Formatted Text</b></div>"
/>
```

**Comment by nicksp** [comment]
As discussed, let's work on this as this is required by the [initial task](https://github.com/x-team/auto-ui/issues/127)'s business goals.

**Comment by bernardodiasc** [comment]
@nick I edited the description of this task to have only the `read only mode` and removed the Markdown functionality of requirements. This is ready to review on PR #146
