### ISSUE TITLE
Extend TextareaEditor with a size option

### ISSUE THREAD

**Issue by Pr0x1m4** [x-team/auto-ui#144]
Issue moved from https://github.com/x-team/auto/issues/1123
Opened by: @ryanchartrand 

On the Portfolio screen, the textarea height on the questions where a developer can type their response is a bit too small. If we increase it, we hope that it will encourage the developer to write longer responses.

Current height: 156px https://d.pr/free/i/USqw2b

New height: 256px https://d.pr/free/i/TJEO5l

**Comment by nicksp** [comment]
Closed via https://github.com/x-team/auto-ui/pull/147
