### ISSUE TITLE
SvgIcon component

### ISSUE THREAD

**Issue by bernardodiasc** [x-team/auto-ui#15]
**Epic** https://github.com/x-team/auto/issues/573

---

Create new component.

<img width="485" alt="screen shot 2017-11-07 at 7 55 06 am" src="https://user-images.githubusercontent.com/131859/32488126-c733a386-c392-11e7-9f19-dc546c74e91a.png">

> Because https://github.com/x-team/auto/blob/master/src/client/components/Icon.js is a font-icon based component (https://github.com/x-team/auto/blob/master/src/client/styles/components/_icon.scss), I'd recommend to migrate it in another task if needed. For this task would be preferred to create an SVG based component.

### Props

```
icon: string,
```

### Behaviour

- `icon` gets a string that maps to different SVG renders

**Comment by joshwnj** [comment]
@bernardodiasc I think we can do without a `className` prop on this component, what do you think?

Sometimes we'll need the icon to have inverted colours, like in #11. Should we have a `foreground` and `background` prop?

**Comment by bernardodiasc** [comment]
Sure thing. I guess the `className` need would appear soon for this one. But there are still option by creating a wrapper element in the parent component that uses that classnames, sometimes this works too.

**Comment by joshwnj** [comment]
I think a wrapper element in the parent component is preferable to a `className` prop. `className` prop is ok in some cases but should be a last resort if there's no other easy option.

**Comment by bernardodiasc** [comment]
Sounds good. Let's try that approach then. 👍

**Comment by nicksp** [comment]
@bernardodiasc Since related PR is merged, we can close this issue.
