### ISSUE TITLE
Profile: Email history module — Single Email Item

### ISSUE THREAD

**Issue by nicksp** [x-team/auto-ui#162]
Part of https://zube.io/x-team/xp-formerly-auto/c/1632

As per parent https://zube.io/x-team/xp-formerly-auto/c/1632 ticket, it would be nice to have an abstracted isolated UI component to represent a single email item, that is gonna be used to make up a conversation list.

Here's the mockup:

![image.png](https://zube.io/files/x-team/731518d4bc2493fe18c2868c9320dc91-image.png)

**Comment by malgorzatajezierska** [comment]
Please refer to the original Sketch file which is up to date.
