### ISSUE TITLE
CollapsibleSection component upgrade

### ISSUE THREAD

**Issue by bernardodiasc** [x-team/auto-ui#17]
**Epic** https://github.com/x-team/auto/issues/573

---

Change styles to:

<img width="964" alt="screen shot 2017-11-07 at 8 15 07 am" src="https://user-images.githubusercontent.com/131859/32488470-d688e3cc-c393-11e7-97b9-e66d02e5bdfb.png">

**Comment by nicksp** [comment]
@bernardodiasc Since related PR is merged, we can close this issue.
