### ISSUE TITLE
Search module - List view results - Applicant Badge UX Improvements

### ISSUE THREAD

**Issue by nicksp** [x-team/auto-ui#172]
As observed [here](https://github.com/x-team/auto/pull/1313#issuecomment-406612944) for better UX we should make a clickable area of the applicant badge the whole badge itself, not just its title and avatar.

![image.png](https://zube.io/files/x-team/717843ae0c5020f5817479bfde1ac10e-image.png)

**Comment by bernardodiasc** [comment]
PR ready for review https://github.com/x-team/auto-ui/pull/177

**Comment by nicksp** [comment]
Closed via https://github.com/x-team/auto-ui/pull/177
