### ISSUE TITLE
Roadmap component

### ISSUE THREAD

**Issue by bernardodiasc** [x-team/auto-ui#19]
**Epic** https://github.com/x-team/auto/issues/573

---

Create new component.

![slice 1](https://user-images.githubusercontent.com/131859/32493231-3f42fc08-c3a4-11e7-8ca1-60cc5d54a432.png)

### Dependencies

- RoadmapLevel component https://github.com/x-team/auto-ui/issues/8
- RoadmapTimelineElement component https://github.com/x-team/auto-ui/issues/10
- Copy component https://github.com/x-team/auto-ui/issues/12
- SvgIcon component https://github.com/x-team/auto-ui/issues/15
- Button component https://github.com/x-team/auto-ui/issues/14

### Props

```
children: node|array,
```

### Behaviour

This component is the layout styles wrapper for Roadmap, the `children` prop should be the render itself, receiving RoadmapLevel, RoadmapTimelineElement, etc.

Example usage:

```
<Roadmap>
  <RoadmapLevel icon="icon-id" heading="lorem ipsum 1" level=1 body={body1Content} isActive />
  <RoadmapLevel icon="icon-id" heading="lorem ipsum 2" level=2 body={body2Content} />
  <RoadmapLevel icon="icon-id" heading="lorem ipsum 3" level=3 body={body3Content} />
  <RoadmapLevel icon="icon-id" heading="lorem ipsum 4" level=4 body={body4Content} />
  <RoadmapLevel icon="icon-id" heading="lorem ipsum 5" level=5 body={body5Content} />
  <RoadmapLevel icon="icon-id" heading="lorem ipsum 6" level=6 body={body6Content} />
  <RoadmapLevel icon="icon-id" heading="lorem ipsum 7" level=7 body={body7Content} />
</Roadmap>
```

**Comment by nicksp** [comment]
just kinda a quick update on dependencies: 
- waiting for one component **to be completed**: https://github.com/x-team/auto-ui/issues/10 
- waiting for one component **to be reviewed and merged**: https://github.com/x-team/auto-ui/issues/14

**Comment by nicksp** [comment]
waiting on #10 to be done in order to accomplish the current one.

**Comment by nicksp** [comment]
unblocked now and ready to be done :)

**Comment by nicksp** [comment]
still work in progress...

**Comment by joshwnj** [comment]
@nicksp I haven't yet seen any obvious way to fix this... There are some additional complications where the vertical line is not exactly centered, and this becomes especially apparent at certain screen widths:

![image](https://user-images.githubusercontent.com/36711/33348390-62516142-d4ea-11e7-9b61-0b9d56c0dfb7.png)

It's frustrating when you get so far, only to run into complications like these! 😆
