### ISSUE TITLE
Fix Actions Click Behavior for ApplicantBadge Component

### ISSUE THREAD

**Issue by relztic** [x-team/auto-ui#191]
Currently, the `ApplicantBadge` component is _not_ focusing the correct card when clicking an action.

![44467201-400b0c00-a5f0-11e8-8524-ff98a2615e37.gif](https://zube.io/files/x-team/843a829da581a87cfc0e63649b1658d5-44467201-400b0c00-a5f0-11e8-8524-ff98a2615e37.gif)

### To Do

Focus the correct applicant card when clicking an action.
So there's _no_ delay when using the dropdown...

### Acceptance Criteria

- [ ] The correct applicant card must be focused when clicking an action.

**Comment by nicksp** [comment]
@relztic Thanks for raising that, as per our discussion 👍
