### ISSUE TITLE
Headbar component

### ISSUE THREAD

**Issue by bernardodiasc** [x-team/auto-ui#20]
**Epic** https://github.com/x-team/auto/issues/573

---

Create new component or migrate https://github.com/x-team/auto/blob/master/src/client/components/XHeader.js and upgrade styles and render.

<img width="834" alt="screen shot 2017-11-07 at 10 28 11 am" src="https://user-images.githubusercontent.com/131859/32493826-70583824-c3a6-11e7-84b1-0ab27cf3e447.png">

### Behaviour

- "Sticky header", fixed on scroll

**Comment by skyronic** [comment]
Closing issue since this is in master now.
