### ISSUE TITLE
HorizontalRuler component

### ISSUE THREAD

**Issue by bernardodiasc** [x-team/auto-ui#21]
**Epic** https://github.com/x-team/auto/issues/573

---

Create new component.

<img width="1010" alt="screen shot 2017-11-07 at 10 41 05 am" src="https://user-images.githubusercontent.com/131859/32494294-2f4f658a-c3a8-11e7-8646-b36ec2bda60d.png">

### Behaviour

Yeah, ya know, for style consistency, create a component that wraps all `<hr/>` usages (even if uses different render of the `<hr/>` tag, the semantics is what counts). Also, this component should rely on margins/paddings to give the desired harmony for horizontal spacing in content compositions.

**Comment by joshwnj** [comment]
Closed in #36
