### ISSUE TITLE
FooterList component

### ISSUE THREAD

**Issue by bernardodiasc** [x-team/auto-ui#23]
**Epic** https://github.com/x-team/auto/issues/573

---

Create new component.

<img width="265" alt="screen shot 2017-11-07 at 10 49 58 am" src="https://user-images.githubusercontent.com/131859/32494609-7208710e-c3a9-11e7-874e-fa578a19e553.png">

### Props

```
title: string,
items: [
  {
    label: string,
    url: string,
  }
]
```

### Behaviour

None specific behaviour.

**Comment by joshwnj** [comment]
@bernardodiasc do you think we need handleClick for each item? Or would `url` suffice?

**Comment by nicksp** [comment]
@bernardodiasc I'd reckon, providing url endpoint would be sufficient to handle generic item click.

**Comment by bernardodiasc** [comment]
Sure thing, if the render uses <a> then it does make sense.
