### ISSUE TITLE
FooterBrands component

### ISSUE THREAD

**Issue by bernardodiasc** [x-team/auto-ui#24]
**Epic** https://github.com/x-team/auto/issues/573

---

Create new component.

<img width="1052" alt="screen shot 2017-11-07 at 10 52 08 am" src="https://user-images.githubusercontent.com/131859/32494692-be877d68-c3a9-11e7-84f3-a12f6e72bc42.png">

### Props

```
brands: [
  {
    title: string,
    image: string,
    url: string,
  }
]
```

### Behaviour

None specific behaviour.

**Comment by joshwnj** [comment]
@bernardodiasc do you think we need `handleClick` for each brand? Or would `url` suffice?

**Comment by bernardodiasc** [comment]
Yeah, this also could work using `url` and rendering with `<a>`. :+1:

**Comment by skyronic** [comment]
Something I've seen in other sites with list of brands - have the logo "darken" on hover, possibly by applying a css transition on the opacity.
