### ISSUE TITLE
Upgrade PageTitle

### ISSUE THREAD

**Issue by joshwnj** [x-team/auto-ui#26]
Upgrade the [`PageTitle`](https://github.com/x-team/auto-ui/blob/master/src/components/PageTitle.js) component to match the new designs:

![image](https://user-images.githubusercontent.com/36711/32523834-2fa08cf2-c471-11e7-96bf-5d88cc874d69.png)

**Comment by richa** [comment]
Issue fixed in :
https://github.com/x-team/auto-ui/pull/38
https://github.com/x-team/auto/pull/627 : WIP
