### ISSUE TITLE
Roadmap from auto-ui does not import propperly

### ISSUE THREAD

**Issue by falcoagustin** [x-team/auto-ui#66]
Currently `auto-ui` repo has a component named `Roadmap`. This component is being imported to the `auto` repo to be used in the applicants journey towards getting hired. By importing it and using it fails to be rendered, this way:
```js
import { Roadmap, RoadmapLevel } from 'auto-ui'
(...)
<Roadmap>
    <RoadmapLevel>
    </RoadmapLevel>
</Roadmap>
```
We can see that if we removed Roadmap component and just use its children those components do get rendered. The error got is the following 
<img width="571" alt="roadmapissue" src="https://user-images.githubusercontent.com/15353019/33679959-e9aac75a-da9e-11e7-9b2d-3181eaf6ef1f.png">

**Comment by nicksp** [comment]
weird issue, tried this on my local instance of `auto` and got exactly the same error. For some reasons it seems working when used inside `auto-ui` build https://x-team.github.io/auto-ui/#!/Roadmap

**Comment by joshwnj** [comment]
It's because `Roadmap` was not exported from the `auto-ui` package :P Fixed in https://github.com/x-team/auto-ui/commit/65b319d06b416ad31c627e2b68015e9e9034bcd5

**Comment by nicksp** [comment]
@joshwnj Right, thanks for spotting that 😃

**Comment by falcoagustin** [comment]
@joshwnj thanks!
