### ISSUE TITLE
Paint textarea in red when error happens for SolutionForm

### ISSUE THREAD

**Issue by falcoagustin** [x-team/auto-ui#79]
## Description

Currently the textarea in `SolutionForm` is shown gray (the same) when an error happens, staying the same color as before, being inconsistent with current `https://join.x-team.com/applicant/:token/submit` solution. 

## How

Paint the textarea borders in red, and shadow the background in a lighter gray this way:
<img width="772" alt="screen shot 2017-12-12 at 3 22 05 pm" src="https://user-images.githubusercontent.com/15353019/33901339-435fa01c-df50-11e7-9d39-bbdbe2acc69c.png">

**Comment by nicksp** [comment]
@falcoagustin This is all looks good and work to me. Just added small adjustments to make code more consistent 😄
