### ISSUE TITLE
RoadmapLevel component

### ISSUE THREAD

**Issue by joshwnj** [x-team/auto-ui#8]
Represents a single "level" in the roadmap screen.

![image](https://user-images.githubusercontent.com/36711/32357989-dd0a9cdc-c095-11e7-88f2-679a0a48793b.png)

## Props

```
icon: url
heading: string
level: number
body: string
isActive: boolean
```
## Behaviour

When `isActive` flag is set, use a highlighted border:

![image](https://user-images.githubusercontent.com/36711/32357806-2ce5b69e-c094-11e7-98d4-19b067f3ab48.png)

**Comment by bernardodiasc** [comment]
@joshwnj let me suggest on approach to create this component:

Starting creating the smaller components:

- https://github.com/x-team/auto-ui/issues/12
- https://github.com/x-team/auto-ui/issues/15

And after that, wrapping up this one.

Please let me know if you agree with that :)

**Comment by bernardodiasc** [comment]
Also include this style variation and CTA button:

<img width="698" alt="screen shot 2017-11-07 at 10 26 34 am" src="https://user-images.githubusercontent.com/131859/32493762-315ff594-c3a6-11e7-8331-1c0abfbfcee2.png">

**Comment by nicksp** [comment]
@bernardodiasc Should this be closed? From what I see, it exists in our codebase already, thus considering it as completed.

**Comment by bernardodiasc** [comment]
:aw-yeah:

**Comment by bernardodiasc** [comment]
Oh no, still missing this detail https://github.com/x-team/auto-ui/blob/master/src/components/RoadmapLevel.js#L49-L52

**Comment by nicksp** [comment]
good catch, it's still in review though :) Wanna fix that :D ?

**Comment by bernardodiasc** [comment]
Hey @nicksp, I'm not available at this moment to resolve this. It should be quite easy, feel free to do it if you want :)

**Comment by nicksp** [comment]
ok, once button components PR is resolved, will fix that. Assigning to myself then.

**Comment by nicksp** [comment]
@joshwnj @bernardodiasc Updated `RoadmapLevel` component and it now seems to be complete 😄
