### ISSUE TITLE
RoadmapHero Component

### ISSUE THREAD

**Issue by richa** [x-team/auto-ui#9]
Represents the hero image and content on the roadmap screen.

![hero](https://user-images.githubusercontent.com/100984/32427142-cac4a116-c2e4-11e7-8803-8addb7fcf2bf.png)

## Props
```
heading: string
content: string
heroUrl: string
```

**Comment by bernardodiasc** [comment]
hey @joshwnj and @richa, let me suggest an approach to create this component:

Starting creating the smaller components:

- Copy component #12 
- Graphic component #13 

And after that, wrap up this one.

Please let me know if you agree with that :)

**Comment by richa** [comment]
@bernardodiasc That sounds better :)

**Comment by joshwnj** [comment]
@richa @bernardodiasc let's also add "Upgrade PageTitle: #26" as a dependency to this.

**Comment by bernardodiasc** [comment]
@joshwnj do you think we could evolve `PageTitle component` to `Copy component`? It's a good way to encapsulate all kinds of typography blocks available in design and maintain their styles and markup in one place.

**Comment by joshwnj** [comment]
@bernardodiasc yes, let's combine them into a single component.  I've left a comment on #12 regarding naming.

**Comment by richa** [comment]
Implemented in:

- https://github.com/x-team/auto-ui/pull/28

**Comment by richa** [comment]
@joshwnj @bernardodiasc (as discussed with @bernardodiasc) : Since PageTitle is already in use in the `auto` repository, there should be separate issue for PageTitle changes where we need to make changes in the `auto` repo as well.

**Comment by nicksp** [comment]
Hey @richa Is this completed and can be closed?

**Comment by nicksp** [comment]
Closing this one as this seems to be done.
